version: '3'

services:
  api:
    container_name: api
    hostname: api
    image: variablecarp571/tunl_assessment_api
    build: .
    command: "yarn dev"
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks:  
      - app-network
  proxy:
    build:
      context: ./nginx
    container_name: web-proxy
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - app-network
  mongo:
    container_name: mongo
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    external: true
